version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/DialogueDown.Visualization/web"
    schedule:
      interval: "weekly"
    groups:
      npm:
        update-types:
          - "minor"
          - "patch"
